[Server]
Mode = "debug"
Addr = "0.0.0.0:80"
ReadTimeout = 60
WriteTimeout = 60

[Database]
Dialect = "mysql"
User = "root"
Password = "123456"
Host = "localhost:3306"
Name = "gin-blog"
Protocol = "tcp"
Charset = "utf8mb4"
ParseTime = "True"
Loc = "Local"
MaxIdleConns = 10
MaxOpenConns = 100
#TablePrefix = "blog_"

[MpConfig]
AppId = "wx4b9fe924b5eeecaf"
Secret = "ff14be916cb29fdd5deb6879987f4f66"

[App]
JwtSecret = 233
RuntimeRootPath = "runtime/"
PrefixUrl = "http://127.0.0.1"
ImageSavePath = "upload/images/"
EmojiSavePath = "emoji/images/"
ImageMaxSize = 5 # 5MB
ImageAllowExts = [".jpg", ".jpeg", ".png"]
ExportSavePath = "export/"
QrCodeSavePath ="qrcode/"
FontSavePath = "fonts/"

[LogSeting]
LogSavePath = "logs/"
LogSaveName = "log"
LogFileExt = "log"
TimeFormat = 20060102

[CaiDan]
XiaoChi = "馄饨,拉面,烩面,热干面,刀削面,油泼面,炸酱面,炒面,重庆小面,米线,酸辣粉,土豆粉,螺狮粉,凉皮儿,麻辣烫,肉夹馍,羊肉汤,炒饭,盖浇饭,卤肉饭,烤肉饭,黄焖鸡米饭,驴肉火烧,川菜,麻辣香锅,火锅,酸菜鱼,烤串,披萨,烤鸭,汉堡,炸鸡,寿司,蟹黄包,煎饼果子,生煎,炒年糕"