[Server]
Mode = "debug"
Addr = "0.0.0.0:8000"
ReadTimeout = 60
WriteTimeout = 60

[Database]
Dialect = "mysql"
User = "root"
Password = "123456"
Host = "localhost:3306"
Name = "gin-blog"
Protocol = "tcp"
Charset = "utf8mb4"
ParseTime = "True"
Loc = "Local"
MaxIdleConns = 10
MaxOpenConns = 100
#TablePrefix = "blog_"

[App]
JwtSecret = 233
RuntimeRootPath = "runtime/"
PrefixUrl = "http://127.0.0.1:8000"
ImageSavePath = "upload/images/"
ImageMaxSize = 5 # 5MB
ImageAllowExts = [".jpg", ".jpeg", ".png"]
ExportSavePath = "export/"
QrCodeSavePath ="qrcode/"
FontSavePath = "fonts/"

[LogSeting]
LogSavePath = "logs/"
LogSaveName = "log"
LogFileExt = "log"
TimeFormat = 20060102